/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as RecoveryProjectIdRouteImport } from './routes/recovery.$projectId'
import { Route as ProjectsProjectIdContentRouteImport } from './routes/projects.$projectId.content'
import { Route as ProjectsProjectIdExportsRouteImport } from './routes/projects.$projectId.exports'
import { Route as ProjectsProjectIdResourcesRouteImport } from './routes/projects.$projectId.resources'
import { Route as ProjectsProjectIdUnitsRouteImport } from './routes/projects.$projectId.units'
import { Route as ProjectsProjectIdValidateRouteImport } from './routes/projects.$projectId.validate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryProjectIdRoute = RecoveryProjectIdRouteImport.update({
  id: '/recovery/$projectId',
  path: '/recovery/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdContentRoute =
  ProjectsProjectIdContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdExportsRoute =
  ProjectsProjectIdExportsRouteImport.update({
    id: '/exports',
    path: '/exports',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdResourcesRoute =
  ProjectsProjectIdResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdUnitsRoute = ProjectsProjectIdUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdValidateRoute =
  ProjectsProjectIdValidateRouteImport.update({
    id: '/validate',
    path: '/validate',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/recovery/$projectId': typeof RecoveryProjectIdRoute
  '/projects/$projectId/content': typeof ProjectsProjectIdContentRoute
  '/projects/$projectId/exports': typeof ProjectsProjectIdExportsRoute
  '/projects/$projectId/resources': typeof ProjectsProjectIdResourcesRoute
  '/projects/$projectId/units': typeof ProjectsProjectIdUnitsRoute
  '/projects/$projectId/validate': typeof ProjectsProjectIdValidateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/recovery/$projectId': typeof RecoveryProjectIdRoute
  '/projects/$projectId/content': typeof ProjectsProjectIdContentRoute
  '/projects/$projectId/exports': typeof ProjectsProjectIdExportsRoute
  '/projects/$projectId/resources': typeof ProjectsProjectIdResourcesRoute
  '/projects/$projectId/units': typeof ProjectsProjectIdUnitsRoute
  '/projects/$projectId/validate': typeof ProjectsProjectIdValidateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/recovery/$projectId': typeof RecoveryProjectIdRoute
  '/projects/$projectId/content': typeof ProjectsProjectIdContentRoute
  '/projects/$projectId/exports': typeof ProjectsProjectIdExportsRoute
  '/projects/$projectId/resources': typeof ProjectsProjectIdResourcesRoute
  '/projects/$projectId/units': typeof ProjectsProjectIdUnitsRoute
  '/projects/$projectId/validate': typeof ProjectsProjectIdValidateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/import'
    | '/projects/$projectId'
    | '/recovery/$projectId'
    | '/projects/$projectId/content'
    | '/projects/$projectId/exports'
    | '/projects/$projectId/resources'
    | '/projects/$projectId/units'
    | '/projects/$projectId/validate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/import'
    | '/projects/$projectId'
    | '/recovery/$projectId'
    | '/projects/$projectId/content'
    | '/projects/$projectId/exports'
    | '/projects/$projectId/resources'
    | '/projects/$projectId/units'
    | '/projects/$projectId/validate'
  id:
    | '__root__'
    | '/'
    | '/import'
    | '/projects/$projectId'
    | '/recovery/$projectId'
    | '/projects/$projectId/content'
    | '/projects/$projectId/exports'
    | '/projects/$projectId/resources'
    | '/projects/$projectId/units'
    | '/projects/$projectId/validate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportRoute: typeof ImportRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  RecoveryProjectIdRoute: typeof RecoveryProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery/$projectId': {
      id: '/recovery/$projectId'
      path: '/recovery/$projectId'
      fullPath: '/recovery/$projectId'
      preLoaderRoute: typeof RecoveryProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/content': {
      id: '/projects/$projectId/content'
      path: '/content'
      fullPath: '/projects/$projectId/content'
      preLoaderRoute: typeof ProjectsProjectIdContentRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/exports': {
      id: '/projects/$projectId/exports'
      path: '/exports'
      fullPath: '/projects/$projectId/exports'
      preLoaderRoute: typeof ProjectsProjectIdExportsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/resources': {
      id: '/projects/$projectId/resources'
      path: '/resources'
      fullPath: '/projects/$projectId/resources'
      preLoaderRoute: typeof ProjectsProjectIdResourcesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/units': {
      id: '/projects/$projectId/units'
      path: '/units'
      fullPath: '/projects/$projectId/units'
      preLoaderRoute: typeof ProjectsProjectIdUnitsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/validate': {
      id: '/projects/$projectId/validate'
      path: '/validate'
      fullPath: '/projects/$projectId/validate'
      preLoaderRoute: typeof ProjectsProjectIdValidateRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdContentRoute: typeof ProjectsProjectIdContentRoute
  ProjectsProjectIdExportsRoute: typeof ProjectsProjectIdExportsRoute
  ProjectsProjectIdResourcesRoute: typeof ProjectsProjectIdResourcesRoute
  ProjectsProjectIdUnitsRoute: typeof ProjectsProjectIdUnitsRoute
  ProjectsProjectIdValidateRoute: typeof ProjectsProjectIdValidateRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdContentRoute: ProjectsProjectIdContentRoute,
  ProjectsProjectIdExportsRoute: ProjectsProjectIdExportsRoute,
  ProjectsProjectIdResourcesRoute: ProjectsProjectIdResourcesRoute,
  ProjectsProjectIdUnitsRoute: ProjectsProjectIdUnitsRoute,
  ProjectsProjectIdValidateRoute: ProjectsProjectIdValidateRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportRoute: ImportRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  RecoveryProjectIdRoute: RecoveryProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
